// <auto-generated />
using CookbookDB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CookbookDB.Migrations
{
    [DbContext(typeof(CookbookDbContext))]
    [Migration("20251125111422_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CookbookDB.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('cookbook.ingredients_id_seq'::regclass)")
                        .HasComment("идентификатор ингредиента");

                    b.Property<decimal?>("Calories")
                        .HasColumnType("numeric")
                        .HasColumnName("calories")
                        .HasComment("ккал");

                    b.Property<decimal?>("Carbs")
                        .HasColumnType("numeric")
                        .HasColumnName("carbs")
                        .HasComment("углеводы");

                    b.Property<decimal?>("Fats")
                        .HasColumnType("numeric")
                        .HasColumnName("fats")
                        .HasComment("жиры");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying")
                        .HasColumnName("name")
                        .HasDefaultValueSql("nextval('cookbook.ingredients_name_seq'::regclass)")
                        .HasComment("название ингредиента");

                    b.Property<decimal?>("Protein")
                        .HasColumnType("numeric")
                        .HasColumnName("protein")
                        .HasComment("белки");

                    b.HasKey("Id")
                        .HasName("ingredient_pk");

                    b.ToTable("ingredient", "cookbook", t =>
                        {
                            t.HasComment("ингредиенты");
                        });
                });

            modelBuilder.Entity("CookbookDB.Models.List", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasComment("идентификатор списка");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("character varying")
                        .HasColumnName("description")
                        .HasComment("описание");

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name")
                        .HasComment("название списка");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id")
                        .HasComment("идентификатор пользователя");

                    b.HasKey("Id")
                        .HasName("list_pk");

                    b.HasIndex("UserId");

                    b.ToTable("list", "cookbook", t =>
                        {
                            t.HasComment("списки рецептов пользователей");
                        });
                });

            modelBuilder.Entity("CookbookDB.Models.ListRecipe", b =>
                {
                    b.Property<int>("ListId")
                        .HasColumnType("integer")
                        .HasColumnName("list_id");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_id");

                    b.ToTable("list_recipes", "cookbook", t =>
                        {
                            t.HasComment("рецепты в списках");
                        });
                });

            modelBuilder.Entity("CookbookDB.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasComment("идентификатор рецепта");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Instruction")
                        .HasColumnType("character varying")
                        .HasColumnName("instruction")
                        .HasComment("инструкция приготовления");

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name")
                        .HasComment("название рецепта");

                    b.Property<int?>("ServingsNumber")
                        .HasColumnType("integer")
                        .HasColumnName("servings_number")
                        .HasComment("количество порций");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("numeric")
                        .HasColumnName("weight")
                        .HasComment("вес всего блюда");

                    b.HasKey("Id")
                        .HasName("recipe_pk");

                    b.ToTable("recipe", "cookbook", t =>
                        {
                            t.HasComment("рецепты");
                        });
                });

            modelBuilder.Entity("CookbookDB.Models.RecipeIngredient", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_id");

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer")
                        .HasColumnName("ingredient_id");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("numeric")
                        .HasColumnName("weight");

                    b.HasKey("RecipeId", "IngredientId")
                        .HasName("recipe_ingredients_pk");

                    b.HasIndex("IngredientId");

                    b.ToTable("recipe_ingredients", "cookbook", t =>
                        {
                            t.HasComment("ингредиенты, использованные в рецептах");
                        });
                });

            modelBuilder.Entity("CookbookDB.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasComment("идентификатор пользователя");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("name")
                        .HasComment("имя пользователя");

                    b.HasKey("Id")
                        .HasName("user_pk");

                    b.ToTable("user", "cookbook", t =>
                        {
                            t.HasComment("пользователи");
                        });
                });

            modelBuilder.Entity("CookbookDB.Models.List", b =>
                {
                    b.HasOne("CookbookDB.Models.User", "User")
                        .WithMany("Lists")
                        .HasForeignKey("UserId")
                        .HasConstraintName("list_user_id_fk");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CookbookDB.Models.RecipeIngredient", b =>
                {
                    b.HasOne("CookbookDB.Models.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .IsRequired()
                        .HasConstraintName("recipe_ingredients_ingredient_id_fk");

                    b.HasOne("CookbookDB.Models.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .IsRequired()
                        .HasConstraintName("recipe_ingredients_recipe_id_fk");

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("CookbookDB.Models.Ingredient", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("CookbookDB.Models.Recipe", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("CookbookDB.Models.User", b =>
                {
                    b.Navigation("Lists");
                });
#pragma warning restore 612, 618
        }
    }
}
